title: "Memory Box: My Bloc"
description: A memory box for my work in BIS490
footer_text: Copyright 2021 - Gary Guiragossian
header_feature_image: ../uploads/blockheader.jpg
header_text: ""
header_text_color: "#000000"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/blocklogo.jpg
favicon: ../uploads/books4screen.jpg
gridlayout: false
fixednavbar: false
upzoom: true
items: []
